baseURL = "https://www.secretfader.com/"
disableHugoGeneratorInject = true 
disableKinds = ["taxonomyTerm"]
languageCode = "en-us"
title = "Nicholas Young"
copyright = "Copyright 2020 Nicholas Young. All rights reserved."
ignoreFiles = ["README.md"]
summaryLength = 28
timeout = 30000
lastmod = [":fileModTime", ":default"]

[params]
author = "Nicholas Young"
description = "Hacker, educator, and artist Nicholas Young."

[params.twitter]
handle = "@secretfader"
url = "https://twitter.com/secretfader"

[params.media]
host = "https://ia801409.us.archive.org/26/items/machinefm"

[imaging]
quality = 75

[outputs]
home = ["html"]
page = ["html"]
section = ["rss", "jsonfeed"]
taxonomy = ["html", "rss", "jsonfeed"]
taxonomyTerm = ["html", "rss", "jsonfeed"]

[outputFormats]
[outputFormats.rss]
baseName = "feed"

[outputFormats.jsonfeed]
baseName = "feed"
mediaType = "application/json"

[outputFormats.reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[permalinks]
writing = "/writing/:year/:month/:slug/"
topics = "/writing/topics/:slug/"
authors = "/writing/author/:slug/"

[taxonomies]
topic = "topics"
author = "authors"

[menu]
[[menu.main]]
identifier = "me"
name = "GitHub"
url = "https://github.com/nicholaswyoung"
weight = 200
