[build]
publish = "public"
command = "hugo"
environment = { HUGO_VERSION = "0.68.3", HUGO_ENV = "production", RUBY_VERSION = "2.6.2", GIT_LFS_SKIP_SMUDGE = "1" }

[context.deploy-preview]
environment = { HUGO_ENV = "staging" }
command = "hugo -b $DEPLOY_PRIME_URL/"
